package com.myspace.wfhrequest_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Reason")
	private java.lang.String reason;
	@org.kie.api.definition.type.Label("Number Of Days")
	private java.lang.Integer numOfDays;

	@org.kie.api.definition.type.Label(value = "Rq Dt")
	private java.lang.Integer reqDt;

	public Request() {
	}

	public java.lang.String getReason() {
		return this.reason;
	}

	public void setReason(java.lang.String reason) {
		this.reason = reason;
	}

	public java.lang.Integer getNumOfDays() {
		return this.numOfDays;
	}

	public void setNumOfDays(java.lang.Integer numOfDays) {
		this.numOfDays = numOfDays;
	}

	public java.lang.Integer getReqDt() {
		return this.reqDt;
	}

	public void setReqDt(java.lang.Integer reqDt) {
		this.reqDt = reqDt;
	}

	public Request(java.lang.String reason, java.lang.Integer numOfDays,
				   java.lang.Integer reqDt) {
		this.reason = reason;
		this.numOfDays = numOfDays;
		this.reqDt = reqDt;
	}

}
